export const LIST_PROPERTIES_SUCCESS = 'LIST_PROPERTIES_SUCCESS';
export const LIST_PROPERTIES_ERROR = 'LIST_PROPERTIES_ERROR';
export const LIST_PROPERTIES_LOADING = 'LIST_PROPERTIES_LOADING';

export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS';
export const GET_PROPERTY_ERROR = 'GET_PROPERTY_ERROR';
export const GET_PROPERTY_LOADING = 'GET_PROPERTY_LOADING';
